### ISSUE TITLE
Make it easier to compile sample games.

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#20]
Wouldn't it be easier for beginners to add '!% +include_path=./lib' to the header of the example files, which makes compilation easier?
```
!% -~S
!% $OMIT_UNUSED_ROUTINES=1
!% +include_path=./lib
```

**Comment by fredrikr** [comment]
We don't think it should be in the file, because:

* Paths may work differently on different platforms.
* Users benefit from learning how to specify the library path on the command line.
* Two of the games (cloak.inf and testbench.inf) can be compiled using either PunyInform or the standard I6 library, and these modes require different paths.

Having said that, we may want to include a brief instruction on how to compile the example games.
