### ISSUE TITLE
Property nw_to missing in #Ifndef OPTIONAL_FULL_DIRECTIONS

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#34]
Isn't the nw_to property missing in #Ifndef OPTIONAL_FULL_DIRECTIONS?
```
#Ifndef OPTIONAL_FULL_DIRECTIONS;
! These have to come outside the other direction props if we DON'T HAVE full directions
Property ne_to;
Property se_to;
Property sw_to;
#EndIf;
```

**Comment by fredrikr** [comment]
This code is more complicated than I'd like it to be, but I can't see a better way to do it.

If the game doesn't use full directions, we would like *not* to create properties for nw_to, ne_to, se_to and sw_to. Unfortunately, due to property aliasing, we still need to create three of them. We managed to make it so that nw_to doesn't have any aliases, and that's why there is one more property free for the game programmer's own use when skipping full directions.
