### ISSUE TITLE
Time broken in v3

### ISSUE THREAD

**Issue by hannessssss** [johanberntsson/PunyInform#39]
Using the code of the manual example of "Time-based Games" and compiling to Z-Code version 3, the clock jumps around on every turn, but in a weird, predictable way.

In Initialise:

SetTime(23 * 60 + 7, 1);

Initial time displayed in the status line: 10:23 (so already wrong).

Moving around:
W --> 18:23
E --> 10:23
E --> 17:23
W --> 10:23
S --> 16:23
N --> 10:23

Compiling the same code to v5, time works as expected.

**Comment by johanberntsson** [comment]
SetTime is already tested in testbench.inf, and from what I can see it works correctly and identical in z3, z5 and Inform I6 mode. Check your game code and compare with the relevant parts of testbench.inf. If this doesn't solve the problem, then upload your game code somewhere and attach a link so I can have a look at it.

**Comment by fredrikr** [comment]
It looks like you have created a global variable before including globals.h. For z3, this makes the hours end up where the minutes should be, and the location id where the hours should be.

**Comment by hannessssss** [comment]
Perfect, moving that global further down indeed fixed the issue. Thank you very much, well spotted!

**Comment by fredrikr** [comment]
Just a note: minimal.inf and the manual outlines the structure of game code, including where globals should go, since we experienced this problem before.

(For z3, the first three global variables have special meaning - their contents are used by the interpreter to print the location, score and moves (or time) on the statuline. For z4+, the game prints its own statusline, so the interpreter doesn't care in which order the globals are defined.)
