### ISSUE TITLE
An object with the concealed attribute, loses it after being taken and dropped

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#47]
```
Object apple "apple" Library
 with
  name 'apple',
  description "it's an invisible apple."
 has concealed;
```
```
The Library
You are in a library.

> get apple
Taken.

> drop apple
Dropped.

> l

The Library
You are in a library.

You can see a apple here.
```

**Comment by fredrikr** [comment]
This is by design.

A concealed object is typically not invisible, but something which is hard to detect. Once you have moved it around though, it shouldn't be hard to detect. If a game author has an object which should be hard to detect even after it has been moved, he/she can easily make that happen.
