### ISSUE TITLE
The title of the help menu is not centered in the window

### ISSUE THREAD

**Issue by auraes** [johanberntsson/PunyInform#96]
I tried with the test file of PunyInform: test-parser.inf, and the Lectrote and frotz(Linux) interpreter.
![menu-min](https://user-images.githubusercontent.com/13295953/147036460-2270496c-8522-4364-8e99-e65a53be580c.png)

**Comment by johanberntsson** [comment]
This is a bug in ext_menu.h. We will fix it, thanks for the report

**Comment by fredrikr** [comment]
This happens because we have diverged from the (broken) behaviour described in DM3 and currently implemented in the standard library, where `item_width` should be set to *half* the width of the item name. In November 2020 we changed this in ext_menu.h so the programmer should set the full item width instead. The test file used the standard library behaviour.

We have now added an option to ext_menu - define the constant EXT_MENU_STDLIB_MOD to make it behave like the standard library. This may come in handy when writing a game that should be compilable with either PunyInform or the standard library.
